"use client";
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {TextGeometry} from 'three/addons/geometries/TextGeometry.js';
import {FontLoader} from 'three/addons/loaders/FontLoader.js';
import fontData from './assets/candle-font.json';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import gsap from 'gsap';
export default function Cake({cut,blown,popSignal,onPop}:{cut:number;blown:boolean;popSignal:number;onPop:()=>void}){
 const mount=useRef<HTMLDivElement>(null),api=useRef<{slices:THREE.Group[];flames:THREE.Group;pop:()=>void}|null>(null),cb=useRef(onPop);cb.current=onPop;const [failed,setFailed]=useState(false);
 useEffect(()=>{if(!mount.current)return;const host=mount.current;let renderer:THREE.WebGLRenderer;try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true});}catch{setFailed(true);return;}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.3;host.appendChild(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,50);camera.position.set(0,4.7,10.8);camera.lookAt(0,1.25,0);const pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment(),env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();pmrem.dispose();scene.add(new THREE.HemisphereLight('#fff6e4','#321b3a',2));const key=new THREE.DirectionalLight('#ffe6bb',4);key.position.set(-3,7,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);scene.add(key);const pinkLight=new THREE.PointLight('#ff3f94',18);pinkLight.position.set(4,3,-2);scene.add(pinkLight);
 const cake=new THREE.Group();scene.add(cake);const material=(color:string,metalness=0,roughness=.35)=>new THREE.MeshStandardMaterial({color,metalness,roughness});const cream=material('#efe1bd',0,.43),ganache=material('#241017',.12,.23),sponge=material('#9a613c',0,.8),gold=material('#d9ab55',.88,.22),cherry=material('#90132d',.1,.17);const add=(g:THREE.Group,geom:THREE.BufferGeometry,mat:THREE.Material,x:number,y:number,z:number)=>{const m=new THREE.Mesh(geom,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;};
 add(cake,new THREE.CylinderGeometry(2.32,2.32,.09,128),gold,0,.03,0);add(cake,new THREE.CylinderGeometry(2.08,1.98,.10,128),ganache,0,-.06,0);
 const slices:THREE.Group[]=[];for(let i=0;i<8;i++){const s=new THREE.Group(),a=i*Math.PI/4;const sector=(radius:number,height:number,y:number,mat:THREE.Material)=>{const sh=new THREE.Shape();sh.moveTo(0,0);sh.absarc(0,0,radius,a,a+Math.PI/4,false);sh.lineTo(0,0);const m=add(s,new THREE.ExtrudeGeometry(sh,{depth:height,bevelEnabled:false,steps:1,curveSegments:32}),mat,0,y,0);m.rotation.x=-Math.PI/2;};sector(1.75,1.35,.1,cream);sector(1.755,.11,.45,sponge);sector(1.756,.06,.56,ganache);sector(1.755,.1,.88,sponge);sector(1.756,.04,.98,ganache);sector(1.78,.11,1.45,ganache);
 for(let j=0;j<6;j++){const t=a+(j+.5)*Math.PI/24;const x=Math.cos(t),z=-Math.sin(t);const dripHeight=.10+Math.abs(Math.sin((i*6+j)*2.31))*.29;const drip=add(s,new THREE.CapsuleGeometry(.065,dripHeight,4,10),ganache,x*1.744,1.4-dripHeight/2,z*1.744);drip.scale.z=.9;}
 for(let j=0;j<3;j++){const t=a+(j+.5)*Math.PI/12;const x=Math.cos(t)*1.46,z=-Math.sin(t)*1.46;for(let petal=0;petal<6;petal++){const p=petal*Math.PI/3;const m=add(s,new THREE.SphereGeometry(.085,12,10),cream,x+Math.cos(p)*.067,1.63,z+Math.sin(p)*.067);m.scale.set(1,1.25,1);}add(s,new THREE.SphereGeometry(.09,16,12),cherry,x,1.79,z);}
 for(let j=0;j<7;j++){const t=a+(j+.5)*Math.PI/28,r=.5+(j%3)*.24;const flake=add(s,new THREE.PlaneGeometry(.07,.035),gold,Math.cos(t)*r,1.566,-Math.sin(t)*r);flake.rotation.x=-Math.PI/2;flake.rotation.z=j*2;}
 cake.add(s);slices.push(s);}
 const font=new FontLoader().parse(fontData);const nums=new TextGeometry('24',{font,size:1.08,depth:.12,curveSegments:12,bevelEnabled:true,bevelThickness:.025,bevelSize:.016,bevelSegments:3});nums.computeBoundingBox();const width=nums.boundingBox!.max.x-nums.boundingBox!.min.x;add(cake,nums,gold,-width/2,1.56,.10);const flames=new THREE.Group();cake.add(flames);for(const x of [-.34,.32]){add(cake,new THREE.CylinderGeometry(.017,.017,.1,8),ganache,x,2.42,.16);const f=add(flames,new THREE.SphereGeometry(.052,16,12),new THREE.MeshBasicMaterial({color:'#ffe5a3'}),x,2.52,.16);f.scale.set(.8,2.2,.8);const light=new THREE.PointLight('#ffaa44',.8,1.5);light.position.copy(f.position);flames.add(light);}
 const shadow=new THREE.Mesh(new THREE.CircleGeometry(4.2,80),new THREE.ShadowMaterial({opacity:.28}));shadow.rotation.x=-Math.PI/2;shadow.position.y=-.13;shadow.receiveShadow=true;scene.add(shadow);
 const balloons:THREE.Group[]=[];const targets:THREE.Mesh[]=[];for(let i=0;i<4;i++){const g=new THREE.Group(),m=add(g,new THREE.SphereGeometry(.44,40,30),material(i%2?'#bd974c':'#a2265e',.82,.16),0,0,0);m.scale.y=1.25;add(g,new THREE.ConeGeometry(.045,.09,8),m.material,0,-.59,0);const pts=Array.from({length:28},(_,j)=>new THREE.Vector3(Math.sin(j*.25+i)*.07,-.63-j*.05,0));g.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts),new THREE.LineBasicMaterial({color:'#cfb5ba',transparent:true,opacity:.65})));g.position.set(i<2?-2.65:2.65,2.2+(i%2)*1.25,-1.1);scene.add(g);balloons.push(g);targets.push(m);}
 const pop=(g:THREE.Group)=>{if(g.userData.popped)return;g.userData.popped=true;gsap.to(g.scale,{x:1.25,y:1.25,z:1.25,duration:.12,onComplete:()=>{g.visible=false;cb.current();}});};api.current={slices,flames,pop:()=>{const g=balloons.find(g=>!g.userData.popped);if(g)pop(g);}};
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let down=false,last=0,start=0;const pd=(e:PointerEvent)=>{down=true;last=start=e.clientX;renderer.domElement.setPointerCapture(e.pointerId);};const pm=(e:PointerEvent)=>{if(down){cake.rotation.y+=(e.clientX-last)*.009;last=e.clientX;}};const pu=(e:PointerEvent)=>{down=false;if(Math.abs(e.clientX-start)<8){const r=host.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(targets.filter(m=>!m.parent?.userData.popped))[0];if(hit)pop(hit.object.parent as THREE.Group);}};const cancel=()=>{down=false;};const kd=(e:KeyboardEvent)=>{if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();cake.rotation.y+=e.key==='ArrowLeft'?-.22:.22;}};host.addEventListener('keydown',kd);renderer.domElement.addEventListener('pointerdown',pd);renderer.domElement.addEventListener('pointermove',pm);renderer.domElement.addEventListener('pointerup',pu);renderer.domElement.addEventListener('pointercancel',cancel);const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(host);resize();const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let frame=0;const tick=(t:number)=>{if(!reduced){if(!down)cake.rotation.y+=.0012;balloons.forEach((g,i)=>g.position.y=2.2+(i%2)*1.25+Math.sin(t*.0009+i)*.15);flames.children.forEach((f,i)=>{if(f instanceof THREE.Mesh)f.scale.y=2.2+Math.sin(t*.012+i)*.2;});}renderer.render(scene,camera);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>{cancelAnimationFrame(frame);ro.disconnect();host.removeEventListener('keydown',kd);scene.traverse(o=>{if(o instanceof THREE.Mesh||o instanceof THREE.Line){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose());}});env.dispose();renderer.dispose();host.replaceChildren();api.current=null;};},[]);
 useEffect(()=>{api.current?.slices.forEach((s,i)=>{const a=(i+.5)*Math.PI/4;gsap.to(s.position,{x:i<cut?Math.cos(a)*.72:0,z:i<cut?-Math.sin(a)*.72:0,duration:1.1,ease:'power3.inOut'});});},[cut]);useEffect(()=>{if(api.current)api.current.flames.visible=!blown;},[blown]);useEffect(()=>{if(popSignal)api.current?.pop();},[popSignal]);return <div className="cake-canvas" ref={mount} tabIndex={0} role="img" aria-label="Gold and chocolate birthday cake. Drag or use arrow keys to rotate. Tap the metallic balloons to pop them.">{failed&&<div className="cake-fallback"><span>24</span><p>3D is unavailable on this device.<br/>You can still make a wish and play the birthday tune.</p></div>}</div>;
}
