"use client";
import {useEffect,useRef,useState} from 'react';
import Cake from './Cake';
import PartyAtmosphere from './PartyAtmosphere';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import confetti from 'canvas-confetti';
import {ArrowUpRight,ArrowDown,Heart,Music2,Disc3,Play,Pause,X,LockKeyhole,RotateCcw,Scissors,Sparkles,Volume2,ChevronLeft,ChevronRight,Mail} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const BIRTHDAY=Date.parse('2026-09-11T00:00:00+05:30');
const ASSET_BASE=process.env.NEXT_PUBLIC_BASE_PATH || '';
const photo=(n:number)=>`${ASSET_BASE}/photos/${String(n).padStart(2,'0')}.jpg`;
const captions=['Ripul on my back. Me carrying the friendship.','Side quests with the boys.','Always got your back.','Same energy, different fits.','The great outdoors. Greater company.','The good ones.','A little cake, a lot of love.','Good company, always.','Dressed up. Still us.','Core memory material.','A very good day.','The boys, in their natural habitat.','Ripul riding shotgun. On my back.','Mountains & the main characters.','The people who make it home.','Carrying this friendship, literally.'];
const note=["24 ka ho rha h bkl, aadhi zindagi toh dost hi raha hai usmein se, holy resume man.","Bitches cum and go but we stay, aint that right? C’est pour la vie frere.","Automate karle apni life bc khud ke liye time nikalna sabse zyada important hai, baaki laal pajame se linen pants tk ladka transform toh full power hogaya hai but leaves some bitches for the bros too.","Utna express nahin ho paa rha idk but you how golden this is, jo bhi hai, yehi hai.","Keep your head up king; geeli puchi max <3 <3 <3"];
function burst(){confetti({particleCount:110,spread:90,origin:{y:.65},colors:['#e5fa76','#fba7c1','#fff5dc','#b9213b'],disableForReducedMotion:true});}
function Jukebox(){const [open,setOpen]=useState(false),[playing,setPlaying]=useState(false),[error,setError]=useState('');const player=useRef<HTMLAudioElement>(null);const playTune=()=>{const a=player.current;if(!a)return;setError('');a.volume=.65;a.play().then(()=>setPlaying(true)).catch(()=>{setPlaying(false);setError('Tap play to start the birthday tune.');});};const toggle=()=>{if(playing){player.current?.pause();setPlaying(false);}else playTune();};useEffect(()=>{const play=()=>{if(player.current)player.current.currentTime=0;playTune();};window.addEventListener('birthday-tune',play);return()=>window.removeEventListener('birthday-tune',play);},[]);return <aside className={`jukebox ${open?'expanded':''}`} aria-label="Vinyl birthday jukebox"><audio ref={player} src={`${ASSET_BASE}/audio/happy-birthday-ripul.wav`} preload="auto" onEnded={()=>setPlaying(false)}/><div className="jukebox-bar"><button className={`record ${playing?'spinning':''}`} onClick={()=>setOpen(!open)} aria-label={open?'Close jukebox':'Open vinyl jukebox'}><Disc3 size={48}/></button><button className="jukebox-label" onClick={()=>setOpen(!open)}><span>RIPUL’S MIDNIGHT RECORD</span><strong>{playing?'Happy Birthday is playing':'Happy Birthday, king.'}</strong></button><button className="round" aria-label={playing?'Pause Happy Birthday':'Play Happy Birthday'} onClick={toggle}>{playing?<Pause size={18}/>:<Play size={18}/>}</button></div>{open&&<div className="jukebox-body"><div className="mini-heading"><span>SIDE A / JUST FOR YOU</span><button onClick={()=>setOpen(false)} aria-label="Collapse jukebox"><X size={18}/></button></div><button className="track selected" onClick={toggle}><span>01 &nbsp; Happy Birthday, Ripul</span>{playing?<Pause size={18}/>:<Play size={18}/>}</button><p>The classic birthday tune, in a soft piano and bell arrangement. No login. Just hit play.</p>{error&&<p role="status">{error}</p>}<a className="song-link" href="https://www.youtube.com/watch?v=G7H1IylNwNU" target="_blank" rel="noreferrer">12 Saal · Bilal Saeed <ArrowUpRight size={18}/></a><details onToggle={e=>{if(e.currentTarget.open){player.current?.pause();setPlaying(false);}}}><summary>Side B / Spotify afterparty</summary><p>Spotify controls playback. Login or short previews may apply. Pause Spotify before playing the birthday tune.</p><iframe title="Spotify party playlist" src="https://open.spotify.com/embed/playlist/37i9dQZF1DXa2PvUpywmC?theme=0" width="100%" height="352" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"/><a href="https://open.spotify.com/playlist/37i9dQZF1DXa2PvUpywmC" target="_blank" rel="noreferrer">Open playlist in Spotify ↗</a></details></div>}</aside>;}
export default function Home(){const [now,setNow]=useState<number|null>(null),[preview,setPreview]=useState(false),[cut,setCut]=useState(0),[blown,setBlown]=useState(false),[popSignal,setPopSignal]=useState(0),[pops,setPops]=useState(0),[letter,setLetter]=useState(false),[selected,setSelected]=useState<number|null>(null),[kiss,setKiss]=useState(0);const unlocked=now!==null&&(now>=BIRTHDAY||preview);const wasOpen=useRef(false);
 useEffect(()=>{setPreview(new URLSearchParams(location.search).get('preview')==='1');setNow(Date.now());const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[]);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const ctx=gsap.context(()=>{if(reduced)return;gsap.from('.entrance',{y:45,opacity:0,duration:1.25,stagger:.17,ease:'power4.out',clearProps:'all'});gsap.to('.title-star',{rotation:360,duration:22,repeat:-1,ease:'none'});gsap.to('.mini-photo',{y:-12,rotation:3,duration:3,repeat:-1,yoyo:true,ease:'sine.inOut'});gsap.utils.toArray<HTMLElement>('.reveal').forEach(el=>gsap.from(el,{y:65,opacity:0,duration:1.1,scrollTrigger:{trigger:el,start:'top 93%'},clearProps:'all'}));gsap.utils.toArray<HTMLElement>('.photo-frame img').forEach((el,i)=>gsap.fromTo(el,{scale:1.12,yPercent:-3},{yPercent:3,scale:1.04,ease:'none',scrollTrigger:{trigger:el,start:'top bottom',end:'bottom top',scrub:1.4}}));gsap.to('.hero h1',{yPercent:-8,ease:'none',scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1.5}});gsap.to('.duo-photo img',{scale:1.07,ease:'none',scrollTrigger:{trigger:'.duo-section',start:'top bottom',end:'bottom top',scrub:1.2}});gsap.to('.finale-orbit',{rotation:50,ease:'none',scrollTrigger:{trigger:'.finale',start:'top bottom',end:'bottom top',scrub:1.5}});});const cards=document.querySelectorAll<HTMLElement>('.tilt-card');const cleanups:Array<()=>void>=[];if(!reduced&&matchMedia('(hover:hover)').matches)cards.forEach(card=>{const move=(e:PointerEvent)=>{const r=card.getBoundingClientRect();gsap.to(card,{rotateY:((e.clientX-r.left)/r.width-.5)*13,rotateX:-((e.clientY-r.top)/r.height-.5)*13,transformPerspective:900,duration:.45});};const leave=()=>{gsap.to(card,{rotateX:0,rotateY:0,duration:.7});};card.addEventListener('pointermove',move);card.addEventListener('pointerleave',leave);cleanups.push(()=>{card.removeEventListener('pointermove',move);card.removeEventListener('pointerleave',leave);});});if(unlocked&&!wasOpen.current){burst();wasOpen.current=true;}return()=>{cleanups.forEach(c=>c());ctx.revert();};},[unlocked]);
 const delta=now===null?null:Math.max(0,BIRTHDAY-now);const values=delta===null?['--','--','--','--']:[Math.floor(delta/86400000),Math.floor(delta/3600000)%24,Math.floor(delta/60000)%60,Math.floor(delta/1000)%60].map(n=>String(n).padStart(2,'0'));
 return <main><PartyAtmosphere/>{preview&&<div className="preview-banner">You’re in the birthday preview. <a href={`${ASSET_BASE}/`}>Return to the real countdown ↗</a></div>}<header><a className="brand" href="#top">R<span>★</span>24<span className="brand-label">THE AFTER HOURS EDITION</span></a><nav>{unlocked?<><a href="#cake">The cake</a><a href="#memories">The evidence</a><button onClick={()=>setLetter(true)}>The letter <ArrowUpRight size={16}/></button></>:<span className="date-label">11 SEPTEMBER 2026 · 00:00 IST</span>}</nav><span className="header-note">Made with way too much love <Heart size={15}/></span></header>
 <section id="top" className={`hero ${unlocked?'is-open':''}`}><div className="hero-top entrance"><span className="eyebrow">{unlocked?'THE WAIT IS OVER. THE LEGEND IS 24.':'SOME THINGS ARE WORTH STAYING UP FOR.'}</span><button className="party-drop" onClick={burst}><Sparkles size={17}/> DROP THE CONFETTI</button></div><div className="title-row entrance"><h1>{unlocked?'HAPPY BIRTHDAY,':'TONIGHT IS YOURS,'}<br/><span>RIPUL</span><span className="title-star" aria-hidden="true">✳</span></h1><div className="side-message"><span className="scribble">12 saal of us.</span><p>24 years of you.<br/>A lifetime to go.</p><div className="mini-photo tilt-card"><img src={photo(1)} alt="Ripul on my back, me in front"/><span>RIPUL ↑ &nbsp; ME ↓ &nbsp; / &nbsp; DAY ONES</span></div></div></div>
 <div className="hero-bottom entrance"><p>{unlocked?<>Aadhi zindagi dost hi raha hai.<br/><strong>Holy resume, man.</strong></>:<>The cake is ready. The boys are here.<br/><strong>Your next chapter opens at midnight.</strong></>}</p>{unlocked?<a className="primary" href="#cake" onClick={()=>window.dispatchEvent(new Event('birthday-tune'))}>Make a wish <Sparkles size={20}/></a>:<div className="countdown" role="timer" aria-label="Time until Ripul's birthday">{values.map((v,i)=><div key={i}><strong>{v}</strong><span>{['DAYS','HOURS','MINUTES','SECONDS'][i]}</span></div>)}</div>}<div className="event-stamp"><span>ONE NIGHT. ONE LEGEND.</span><strong>11.09.26</strong><span>{unlocked?'HAPPY 24, KING.':'MIDNIGHT · INDIA TIME'}</span></div></div>
 {!unlocked&&<div className="locked-strip"><LockKeyhole size={16}/><span>A whole little universe, wrapped up just for you. It opens automatically.</span></div>}
 </section>
 {unlocked?<><div className="ticker" aria-hidden="true"><div>24 KA HO GAYA ★ C’EST POUR LA VIE, FRÈRE ★ KEEP YOUR HEAD UP KING ★ 12 SAAL OF US ★ 24 KA HO GAYA ★ C’EST POUR LA VIE, FRÈRE ★</div></div>
 <section className="cake-section" id="cake"><div className="section-heading reveal"><div><span className="eyebrow">01 / THE BIRTHDAY RITUAL</span><h2>A wish. A slice.<br/><em>A little chaos.</em></h2></div><p>Drag the cake to spin it.<br/>Pop the balloons. Go on, you’re 24.</p></div><div className="cake-stage"><div className="cake-sticker">Midnight ganache.<br/>Gold-standard chaos.</div><Cake cut={cut} blown={blown} popSignal={popSignal} onPop={()=>{setPops(p=>p+1);burst();}}/><div className="cake-status" aria-live="polite">{cut===8?'Everybody gets a slice. That’s our boy.':cut>0?`${cut} of 8 slices cut. Save some for the boys.`:blown?'Wish made. Now attack the cake.':'One big wish. No peeking.'}</div></div><div className="cake-actions"><button className="primary" onClick={()=>{setBlown(true);burst();window.dispatchEvent(new Event('birthday-tune'));}} disabled={blown}><Sparkles size={19}/>{blown?'Wish made ♡':'Blow out candles'}</button><button className="outline" disabled={cut===8} onClick={()=>{setCut(c=>Math.min(8,c+1));burst();}}><Scissors size={19}/>{cut===8?'Cake demolished':'Cut a slice'}</button><button className="outline" disabled={pops>=4} onClick={()=>setPopSignal(p=>p+1)}>Pop a balloon · {pops}/4</button><button className="reset" onClick={()=>{setCut(0);setBlown(false);}}><RotateCcw size={18}/> Reset cake</button></div></section>
 <section className="duo-section"><div className="duo-photo reveal"><img src={photo(1)} alt="Ripul wearing yellow on my back, me wearing pink in front"/><span className="ripul-tag">RIPUL / THE BIRTHDAY MENACE ↗</span><span className="me-tag">ME / THE LIFETIME SUPPORT SYSTEM ↗</span></div><div className="duo-copy reveal"><span className="eyebrow">THE REAL RIDE OR DIE</span><h2>On my back.<br/><em>By my side.</em><br/>For life.</h2><p>12 saal se is bande ko carry kar raha hoon.<br/>Literally. Photographic evidence attached.</p><button className="primary" onClick={burst}>12 years. Still carrying. <Heart size={19}/></button><div className="duo-stats"><div><strong>12</strong><span>YEARS OF US</span></div><div><strong>24</strong><span>YEARS OF RIPUL</span></div><div><strong>∞</strong><span>MORE TO GO</span></div></div></div></section><section className="memories" id="memories"><div className="section-heading reveal"><div><span className="eyebrow">02 / THE CAMERA ROLL DOESN’T LIE</span><h2>Same idiots.<br/><em>Golden memories.</em></h2></div><p>Some friendships deserve a whole archive.<br/>Tap a photo. Stay a little.</p></div><div className="photo-wall">{[14,10,3,7,5,4,6,11,9,8,15,1,2,12,13,16].map((n,i)=><button className={`photo-card reveal tilt-card photo-${i%4}`} key={n} onClick={()=>setSelected(n)}><div className="photo-frame"><img src={photo(n)} alt={captions[n-1]} loading="lazy"/></div><span className="photo-caption">{captions[n-1]}</span><span className="photo-number">MEMORY {String(n).padStart(2,'0')} <ArrowUpRight size={16}/></span></button>)}</div></section>
 <section className="letter-section" id="letter"><div className="letter-left reveal"><span className="eyebrow">03 / FROM YOUR DAY ONE</span><h2>12 saal.<br/><em>Pour la vie.</em></h2><p>“Utna express nahin ho paa rha idk<br/>but you how golden this is.”</p><span className="scribble">Some things don’t need perfect words.</span></div><button className="letter-card reveal" onClick={()=>setLetter(true)}><span className="letter-card-top">PERSONAL DELIVERY <Mail size={24}/></span><span className="letter-to">To Ripul,<br/>my brother.</span><span className="letter-seal"><Heart fill="currentColor" size={30}/></span><span className="letter-card-bottom">A little roast. A lot of love. <ArrowUpRight size={24}/></span></button></section>
 <section className="finale reveal"><span className="eyebrow">THE AFTERPARTY IS FOREVER.</span><div className="finale-orbit" aria-hidden="true">24 / RIPUL / 24 / RIPUL /</div><h2>Keep your<br/>head up, <em>king.</em></h2><button className="kiss-button" onClick={()=>{setKiss(k=>k+1);burst();}}><Heart size={22} fill="currentColor"/> Geeli puchi max {kiss>0&&`× ${kiss}`}</button><p>C’est pour la vie, frère. ♡</p></section></>:<section className="teaser"><div className="teaser-photos"><img src={photo(14)} alt="The boys together in the mountains"/><img src={photo(10)} alt="Friends sharing a laugh"/><img src={photo(3)} alt="A piggyback in the mountains"/></div><p className="scribble">The best part has always been us.</p><span>12 SAAL · BILAL SAEED &nbsp; / &nbsp; OUR KIND OF SOUNDTRACK</span></section>}
 <footer><a className="brand" href="#top">R<span>★</span>24</a><p>For Ripul. From the people who stay.</p><span>11 SEPTEMBER 2026 ♡</span></footer><Jukebox/>
 <Dialog open={letter} onOpenChange={setLetter}><DialogContent className="letter-modal"><DialogTitle className="letter-modal-title">12 saal. A lifetime to go.</DialogTitle><DialogDescription className="letter-dedication">For Ripul, on your 24th. ♡</DialogDescription><div className="note-body">{note.map((p,i)=><p key={i}>{p}</p>)}<span className="scribble">C’est pour la vie, frère.</span></div></DialogContent></Dialog>
 <Dialog open={selected!==null} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent className="photo-modal"><DialogTitle>{selected!==null?captions[selected-1]:''}</DialogTitle><DialogDescription>From our camera roll, with love.</DialogDescription>{selected!==null&&<><img src={photo(selected)} alt={captions[selected-1]}/><div className="photo-controls"><button className="outline" onClick={()=>setSelected(selected===1?16:selected-1)}><ChevronLeft size={20}/> Previous</button><span>{selected} / 16</span><button className="outline" onClick={()=>setSelected(selected===16?1:selected+1)}>Next <ChevronRight size={20}/></button></div></>}</DialogContent></Dialog>
 </main>;
}
